# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dotnettestfromgithubdeploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mydockerexamplecontainerregister.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_909c45d5e7bf48dca15c2c665bf3b2b8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_39cc4eb33f4f490eb4c86ac0cae41677 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mydockerexamplecontainerregister.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_909c45d5e7bf48dca15c2c665bf3b2b8 }}/Abhidkiya:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dotnettestfromgithubdeploy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c81c49075cdf41e8824ad27ea4e3d744 }}
        images: 'mydockerexamplecontainerregister.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_909c45d5e7bf48dca15c2c665bf3b2b8 }}/Abhidkiya:${{ github.sha }}'