# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webname12345

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mydockerexamplecontainerregister.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ae88c2aad2cd4d1eb2fbab92df11ddd0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_78b8a0bf7bfc45a8898bac4a00aadc8a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mydockerexamplecontainerregister.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae88c2aad2cd4d1eb2fbab92df11ddd0 }}/dockerexample:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webname12345'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a49a23ef4c144efeba42df2d8b7a382b }}
        images: 'mydockerexamplecontainerregister.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae88c2aad2cd4d1eb2fbab92df11ddd0 }}/dockerexample:${{ github.sha }}'